name: goomba
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  camera: ^0.10.4
  permission_handler: ^10.2.0
  gap: ^3.0.0
  go_router: ^6.5.6
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_svg: ^2.0.5
  reactive_forms: ^14.3.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.2.2
  cloud_functions: ^4.1.0
  cloud_firestore: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/
    - assets/icons/
    - assets/images/
    - assets/images/characters/
    - assets/images/cups/
    - assets/images/maps/
